const ARTICLES = [
  {
    id: "migration-residual-assets-2026-06",
    title: "定着率では測れない - 移住定住で「残る資産」を見る視点",
    category: "課題発見",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["migration"],
    summary: "「何人来たか」「何%残ったか」では地域に何が残るかを測れない。事業・関係・仕組みの 3 資産で評価する視点と、評価軸を組み替えると施策がどう変わるかを整理。",
  },
  {
    id: "migration-longterm-cases-2026-06",
    title: "17 年、15 年継続する町に共通するもの - 海士町・神山町の長期視点",
    category: "アイデア",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["migration"],
    summary: "海士町と神山町に共通するのは「長期継続」と「仕組み化」。事例の表面ではなく、20 年続いた 5 つの設計原則を読み解く。",
  },
  {
    id: "furusato-nozei-asset-question-2026-06",
    title: "ふるさと納税は地方財源か、それとも関係資産か",
    category: "課題発見",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["furusato-nozei"],
    summary: "ふるさと納税を短期収入として扱うか、長期の関係資産として扱うか。評価軸の選択が、制度改正への脆弱性と長期の安定性を分ける。",
  },
  {
    id: "furusato-nozei-transition-2026-06",
    title: "寄附から関係人口へ - ふるさと納税の 4 つの転換",
    category: "アイデア",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["furusato-nozei"],
    summary: "短期収入から長期関係資産への移行に必要な 4 つの具体策と、KPI の組み替えを整理。寄附者を地域のファンに育てる投資戦略。",
  },
  {
    id: "vacant-houses-perspective-2026-06",
    title: "空き家を負担から資源に - 視点転換が変える施策",
    category: "課題発見",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["vacant-houses"],
    summary: "「いかに減らすか」から「誰が、何のために使うか」へ。住む ・ 働く ・ 集まるの 3 用途で統合的に組み立てる視点を整理。",
  },
  {
    id: "vacant-houses-onomichi-2026-06",
    title: "20 年継続が作る空き家再生 - 尾道に学ぶ仕組み",
    category: "アイデア",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["vacant-houses"],
    summary: "尾道空き家再生プロジェクトの 20 年。設備でも補助金でもなく、組織 ・ 関わり方 ・ 循環という仕組み資産を残した 5 つの設計原則。",
  },
  {
    id: "child-poverty-structure-2026-06",
    title: "子どもの貧困と教育格差 - 世代を跨ぐ連鎖を断つ視点",
    category: "課題発見",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["child-poverty"],
    summary: "北海道の子どもの貧困率 18% 、ひとり親世帯 50% 近く。経済支援を超えた仕組み転換と、わたしたちの日常でできる関わり方。",
  },
  {
    id: "food-self-sufficiency-waste-2026-06",
    title: "食料自給率 220% と廃棄の同居 - 北海道のフードロス構造",
    category: "課題発見",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["food-waste-self-sufficiency"],
    summary: "北海道の自給率 220% は全国突出、一方で流通 ・ 加工段階のロスは膨大。生産大国の影に潜む構造的廃棄と、わたしたちの食卓でできること。",
  },
  {
    id: "succession-primary-industry-2026-06",
    title: "黒字でも廃業 - 北海道の一次産業の担い手構造",
    category: "課題発見",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["succession"],
    summary: "北海道の農業 ・ 漁業 ・ 林業は黒字でも廃業に至る事業者が少なくない。承継 = 人 + 価値再設計 + 販路という三層構造と、わたしたちにできる関わり方。",
  },
  {
    id: "regional-recruitment-structure-2026-06",
    title: "地域企業の採用難 - なぜ給与 UP では届かないのか",
    category: "課題発見",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["regional-business-recruitment"],
    summary: "中小企業 ・ サービス ・ 建設 ・ 介護 ・ 飲食 ・ 製造業のいずれも深刻な採用難。給与差 ・ 情報接点 ・ 移住障壁 ・ ブランド力不在の 4 構造要因を読み解く。",
  },
  {
    id: "regional-recruitment-transition-2026-06",
    title: "地域全体で『働く魅力』を設計する - 採用の 4 つの転換",
    category: "アイデア",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["regional-business-recruitment"],
    summary: "個別企業の給与競争でなく、業界 ・ 主体 ・ 接点 ・ 指標を組み替える 4 つの転換で、地域全体での採用ブランディングを設計する。",
  },
  {
    id: "youth-leaving-reasons-2026-06",
    title: "若者が地域を離れる - 5 つの理由と地域に残る選択肢の作り方",
    category: "課題発見",
    publishedAt: "2026-06-12",
    readMinutes: 4,
    relatedIssues: ["regional-business-recruitment", "migration", "youth-support"],
    summary: "若者の地域離脱を「個人の選択」と諦めず、5 つの理由を構造的に読み解き、残る ・ 戻る ・ 関わるの 3 つの選択肢を地域に作る視点。",
  },
  {
    id: "bear-conflict-structure-2026-06",
    title: "ヒグマと共存できる地域づくり - 北海道のヒグマ対応の構造",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["bear-conflict"],
    summary: "道内ヒグマ生息数約 1.2 万頭、出没年 1 万件超。駆除か共存かではなく、5 つの構造要因 ( 人口減 ・ 林業衰退 ・ 緩衝帯消失 ・ 個体数増 ・ 学習 ) を統合的に扱う視点。",
  },
  {
    id: "semiconductor-rapidus-economy-2026-06",
    title: "ラピダス進出が変える北海道経済 - 半導体集積の構造と影響",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["semiconductor"],
    summary: "ラピダス 5 兆円投資、千歳 ・ 苫小牧に半導体産業集積。雇用 ・ サプライチェーン ・ 地域インフラへの影響を構造から読み解く。",
  },
  {
    id: "jr-hokkaido-future-structure-2026-06",
    title: "JR 北海道は維持できるか - 鉄道存続と地域インフラの構造",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["jr-hokkaido-future"],
    summary: "13 路線で「維持困難」表明、廃線進行中。鉄道存続を「赤字 vs 黒字」ではなく、地域インフラの構造として読み解く。",
  },
  {
    id: "tourism-sustainability-dual-2026-06",
    title: "北海道観光の二重構造 - オーバーツーリズムと過疎観光の同時進行",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["tourism-sustainability"],
    summary: "ニセコ過熱と過疎観光地の衰退が同時進行。「観光客を呼ぶ」だけでなく、観光持続性の構造を読み解く。",
  },
  {
    id: "regional-medical-structure-2026-06",
    title: "北海道の地域医療 - 無医地区 137 と医師偏在の構造",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["regional-medical"],
    summary: "道内無医地区 137、医師は札幌 ・ 都市部集中。地域医療を「個別の医師確保」ではなく、構造的な仕組みとして読み解く。",
  },
  {
    id: "decarbonization-renewable-2026-06",
    title: "北海道の脱炭素 - 再エネ大国の実装課題と地域経済",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["decarbonization"],
    summary: "再エネポテンシャル日本一の北海道、だが系統制約と地域経済への波及が課題。脱炭素を地域経済の競争優位に変える構造。",
  },
  {
    id: "disaster-resilience-2026-06",
    title: "北海道の防災 - 大雪 ・ 地震 ・ 津波の複合リスク",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["disaster"],
    summary: "北海道は大雪 ・ 地震 ・ 津波 ・ 火山の複合災害リスク。BCP と住民の備えで地域レジリエンスを構造化する視点。",
  },
  {
    id: "multicultural-living-2026-06",
    title: "外国人住民との暮らし - 30 年継続する地域に学ぶ多文化共生",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["multicultural", "foreign-resident-support"],
    summary: "道内外国人住民約 4 万人。「労働力」から「生活者」への転換と、大泉町 ・ 浜松市の 30 年継続事例に学ぶ多文化共生の構造。",
  },
  {
    id: "aging-single-household-2026-06",
    title: "単身高齢者 30% 時代の北海道 - 地域ケアの構造的課題",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["aging-care"],
    summary: "道内高齢化率 33% 、単身世帯急増。介護 ・ 認知症 ・ 在宅医療を「個別ケア」ではなく地域包括ケアの構造として読み解く。",
  },
  {
    id: "ainu-culture-coexistence-2026-06",
    title: "アイヌ文化と現代北海道 - 共生の歴史と未来への構造",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["ainu-culture"],
    summary: "アイヌ施策推進法 2019 ・ ウポポイ開設後、アイヌ文化の継承 ・ 経済参加 ・ 偏見の解消が新たな段階に。北海道のアイデンティティとして読み解く。",
  },
  {
    id: "childcare-shortage-structure-2026-06",
    title: "保育所待機児童と保育士不足 - 北海道の子育てインフラ構造",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["childcare-shortage"],
    summary: "札幌待機児童 100 人前後、保育士有効求人倍率 2.5 倍超。「施設を増やす」だけでない構造的な子育てインフラの作り方。",
  },
  {
    id: "school-consolidation-structure-2026-06",
    title: "学校統合と地域 - 小規模校の存続と教育環境の構造",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["school-consolidation"],
    summary: "道内小規模校の統廃合が進む一方、地域から学校が消える影響は深刻。「規模の効率」と「地域の核」の両立を読み解く。",
  },
  {
    id: "infra-aging-resilience-2026-06",
    title: "インフラ老朽化と維持 - 道路 ・ 橋 ・ 水道の長期戦略",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["infra-aging"],
    summary: "高度成長期建設のインフラが一斉に更新期。「すべて維持」と「集約 ・ 撤退」の選択を構造的に判断する視点。",
  },
  {
    id: "cost-of-living-hokkaido-2026-06",
    title: "北海道の暮らしのコスト - 暖房費 ・ 物価 ・ 家計の構造",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["cost-of-living"],
    summary: "暖房費は本州の数倍、食料品 ・ ガソリンも物流コスト分高い。北海道の暮らしのコスト構造と、地域経済への影響を読み解く。",
  },
  {
    id: "fisheries-climate-change-2026-06",
    title: "北海道の漁業と気候変動 - 海洋環境の変化が変える水産業",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["fisheries-climate"],
    summary: "ホタテ ・ サンマ ・ サケの不漁 ・ 漁獲変動。海洋温暖化と漁業の構造的な対応を読み解く。",
  },
  {
    id: "bear-coexistence-cases-2026-06",
    title: "ヒグマと共存する自治体の取り組み - 知床 ・ 大牟田に学ぶ長期事例",
    category: "アイデア",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["bear-conflict"],
    summary: "知床財団 30 年 ・ 福岡県大牟田市 20 年継続事例から、ヒグマと共存できる地域を作る 5 つの設計原則を学ぶ。",
  },
  {
    id: "semiconductor-rapidus-strategy-2026-06",
    title: "ラピダスを核に北海道半導体集積を作る - 5 つの戦略",
    category: "アイデア",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["semiconductor"],
    summary: "ラピダス 1 社依存から複数集積の起点へ。住宅 ・ 人材 ・ 関連産業 ・ 教育 ・ 国際性の 5 戦略で半導体クラスターを 20 年で育てる。",
  },
  {
    id: "elderly-care-staff-structure-2026-06",
    title: "介護人材 32 万人不足時代の地域ケア - 構造的課題と長期戦略",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["elderly-care-staff", "aging-care"],
    summary: "全国 32 万人介護人材不足 ( 2025 ) 、北海道は広域分散で特に深刻。介護を「個別職員確保」ではなく構造課題として読み解く。",
  },
  {
    id: "forest-circulation-structure-2026-06",
    title: "北海道の林業と森林循環 - 木材自給率と地域経済の構造",
    category: "課題発見",
    publishedAt: "2026-06-13",
    readMinutes: 4,
    relatedIssues: ["forest-circulation"],
    summary: "道内森林面積 554 万 ha、木材自給率上昇中。林業を「縮小産業」ではなく「森林循環の核」として再定義する構造。",
  },
];